### PR TITLE
Filter razed road in Luxembourg

### PR DESCRIPTION
**Pull request by grischard**

### CODE REVIEW

**Comment by grischard** [comment]
Replaces #428

**Comment by grischard** [comment]
@jbelien would it please be possible to have a look at this PR? It removes a razed road from the results in Luxembourg.

**Comment by jbelien** [comment]
As you see there are merge conflicts, so it can't be merged!
Please revert changes in the JSON files and only commit the change in the filter.

**Comment by grischard** [comment]
@jbelien done! I think it was the CI bot that re-ran the process, causing the conflicts.

**Comment by grischard** [comment]
Thank you!

**Pull request merged**
